# Generated by Django 4.0.4 on 2022-11-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('cs_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('adr', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.CharField(max_length=3)),
                ('occupation', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
